# Generated by Django 4.0.10 on 2023-11-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_be_shared',
            field=models.BooleanField(default=False),
        ),
    ]
